//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace live.courses.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetUser
    {
        public AspNetUser()
        {
            this.AspNetUserClaims = new HashSet<AspNetUserClaim>();
            this.AspNetUserLogins = new HashSet<AspNetUserLogin>();
            this.Course_Members = new HashSet<Course_Members>();
            this.Room_Members = new HashSet<Room_Members>();
            this.Work_group_members = new HashSet<Work_group_members>();
            this.AspNetRoles = new HashSet<AspNetRole>();
            this.comments = new HashSet<comment>();
            this.likes = new HashSet<like>();
            this.posts = new HashSet<post>();
            this.replies = new HashSet<reply>();
            this.notifications = new HashSet<notification>();
            this.inst_previous_courses = new HashSet<inst_previous_courses>();
            this.course_comment = new HashSet<course_comment>();
            this.group_comment = new HashSet<group_comment>();
        }
    
        public string Id { get; set; }
        public string Email { get; set; }
        public bool EmailConfirmed { get; set; }
        public string PasswordHash { get; set; }
        public string SecurityStamp { get; set; }
        public string PhoneNumber { get; set; }
        public bool PhoneNumberConfirmed { get; set; }
        public bool TwoFactorEnabled { get; set; }
        public Nullable<System.DateTime> LockoutEndDateUtc { get; set; }
        public bool LockoutEnabled { get; set; }
        public int AccessFailedCount { get; set; }
        public string UserName { get; set; }
        public string Country { get; set; }
        public string State { get; set; }
        public string Gender { get; set; }
        public string Photo { get; set; }
        public string Apout { get; set; }
        public string AnotherAccount { get; set; }
        public Nullable<bool> IsInstructor { get; set; }
        public string GuaranteeDecument { get; set; }
        public string IdCard { get; set; }
        public string Residence { get; set; }
        public string Photograph { get; set; }
        public string IdCardBack { get; set; }
        public string facebookAccount { get; set; }
        public string twitterAccount { get; set; }
        public string jobTitle { get; set; }
        public string DeviceToken { get; set; }
    
        public virtual ICollection<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual ICollection<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual ICollection<Course_Members> Course_Members { get; set; }
        public virtual ICollection<Room_Members> Room_Members { get; set; }
        public virtual ICollection<Work_group_members> Work_group_members { get; set; }
        public virtual ICollection<AspNetRole> AspNetRoles { get; set; }
        public virtual ICollection<comment> comments { get; set; }
        public virtual ICollection<like> likes { get; set; }
        public virtual ICollection<post> posts { get; set; }
        public virtual ICollection<reply> replies { get; set; }
        public virtual ICollection<notification> notifications { get; set; }
        public virtual ICollection<inst_previous_courses> inst_previous_courses { get; set; }
        public virtual ICollection<course_comment> course_comment { get; set; }
        public virtual ICollection<group_comment> group_comment { get; set; }
    }
}
