//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace live.courses.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class adv_coursesEntities : DbContext
    {
        public adv_coursesEntities()
            : base("name=adv_coursesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<certificate> certificates { get; set; }
        public virtual DbSet<course> courses { get; set; }
        public virtual DbSet<Course_Members> Course_Members { get; set; }
        public virtual DbSet<course_tags> course_tags { get; set; }
        public virtual DbSet<friend> friends { get; set; }
        public virtual DbSet<message> messages { get; set; }
        public virtual DbSet<room> rooms { get; set; }
        public virtual DbSet<Room_Members> Room_Members { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tag> tags { get; set; }
        public virtual DbSet<work_group> work_group { get; set; }
        public virtual DbSet<Work_group_members> Work_group_members { get; set; }
        public virtual DbSet<work_group_tags> work_group_tags { get; set; }
        public virtual DbSet<comment> comments { get; set; }
        public virtual DbSet<like> likes { get; set; }
        public virtual DbSet<post> posts { get; set; }
        public virtual DbSet<reply> replies { get; set; }
        public virtual DbSet<notification> notifications { get; set; }
        public virtual DbSet<inst_previous_courses> inst_previous_courses { get; set; }
        public virtual DbSet<course_comment> course_comment { get; set; }
        public virtual DbSet<group_comment> group_comment { get; set; }
    
        public virtual int accept_friend_request(string reciver, string sender)
        {
            var reciverParameter = reciver != null ?
                new ObjectParameter("reciver", reciver) :
                new ObjectParameter("reciver", typeof(string));
    
            var senderParameter = sender != null ?
                new ObjectParameter("sender", sender) :
                new ObjectParameter("sender", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("accept_friend_request", reciverParameter, senderParameter);
        }
    
        public virtual int add_security_info(string id, string guarantee, string idcard, string idcardback, string residence, string photograph)
        {
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            var guaranteeParameter = guarantee != null ?
                new ObjectParameter("guarantee", guarantee) :
                new ObjectParameter("guarantee", typeof(string));
    
            var idcardParameter = idcard != null ?
                new ObjectParameter("idcard", idcard) :
                new ObjectParameter("idcard", typeof(string));
    
            var idcardbackParameter = idcardback != null ?
                new ObjectParameter("idcardback", idcardback) :
                new ObjectParameter("idcardback", typeof(string));
    
            var residenceParameter = residence != null ?
                new ObjectParameter("residence", residence) :
                new ObjectParameter("residence", typeof(string));
    
            var photographParameter = photograph != null ?
                new ObjectParameter("photograph", photograph) :
                new ObjectParameter("photograph", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("add_security_info", idParameter, guaranteeParameter, idcardParameter, idcardbackParameter, residenceParameter, photographParameter);
        }
    
        public virtual int archive_course(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("archive_course", idParameter);
        }
    
        public virtual int archive_work_group(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("archive_work_group", idParameter);
        }
    
        public virtual int create_room_for_course(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("create_room_for_course", idParameter);
        }
    
        public virtual int create_room_for_work_group(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("create_room_for_work_group", idParameter);
        }
    
        public virtual int edit_user(string id, string email, string phone, string username, string country, string state, string gender, string photo, string apout, string another_account, string facebookAccount, string twitterAccount, string jobTitle)
        {
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var phoneParameter = phone != null ?
                new ObjectParameter("Phone", phone) :
                new ObjectParameter("Phone", typeof(string));
    
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var countryParameter = country != null ?
                new ObjectParameter("country", country) :
                new ObjectParameter("country", typeof(string));
    
            var stateParameter = state != null ?
                new ObjectParameter("state", state) :
                new ObjectParameter("state", typeof(string));
    
            var genderParameter = gender != null ?
                new ObjectParameter("gender", gender) :
                new ObjectParameter("gender", typeof(string));
    
            var photoParameter = photo != null ?
                new ObjectParameter("photo", photo) :
                new ObjectParameter("photo", typeof(string));
    
            var apoutParameter = apout != null ?
                new ObjectParameter("apout", apout) :
                new ObjectParameter("apout", typeof(string));
    
            var another_accountParameter = another_account != null ?
                new ObjectParameter("another_account", another_account) :
                new ObjectParameter("another_account", typeof(string));
    
            var facebookAccountParameter = facebookAccount != null ?
                new ObjectParameter("facebookAccount", facebookAccount) :
                new ObjectParameter("facebookAccount", typeof(string));
    
            var twitterAccountParameter = twitterAccount != null ?
                new ObjectParameter("twitterAccount", twitterAccount) :
                new ObjectParameter("twitterAccount", typeof(string));
    
            var jobTitleParameter = jobTitle != null ?
                new ObjectParameter("jobTitle", jobTitle) :
                new ObjectParameter("jobTitle", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("edit_user", idParameter, emailParameter, phoneParameter, usernameParameter, countryParameter, stateParameter, genderParameter, photoParameter, apoutParameter, another_accountParameter, facebookAccountParameter, twitterAccountParameter, jobTitleParameter);
        }
    
        public virtual int finish_course_for_all_members(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("finish_course_for_all_members", idParameter);
        }
    
        public virtual int finish_course_for_one_member(string user_id, Nullable<int> course_id)
        {
            var user_idParameter = user_id != null ?
                new ObjectParameter("user_id", user_id) :
                new ObjectParameter("user_id", typeof(string));
    
            var course_idParameter = course_id.HasValue ?
                new ObjectParameter("course_id", course_id) :
                new ObjectParameter("course_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("finish_course_for_one_member", user_idParameter, course_idParameter);
        }
    
        public virtual ObjectResult<Get_all_archived_courses_Result> Get_all_archived_courses()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_all_archived_courses_Result>("Get_all_archived_courses");
        }
    
        public virtual ObjectResult<get_all_archived_courses_for_user_Result> get_all_archived_courses_for_user(string id)
        {
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_all_archived_courses_for_user_Result>("get_all_archived_courses_for_user", idParameter);
        }
    
        public virtual ObjectResult<Get_all_archived_groups_Result> Get_all_archived_groups()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_all_archived_groups_Result>("Get_all_archived_groups");
        }
    
        public virtual ObjectResult<get_all_archived_work_groups_for_user_Result> get_all_archived_work_groups_for_user(string id)
        {
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_all_archived_work_groups_for_user_Result>("get_all_archived_work_groups_for_user", idParameter);
        }
    
        public virtual ObjectResult<get_all_course_mempers_Result> get_all_course_mempers(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_all_course_mempers_Result>("get_all_course_mempers", idParameter);
        }
    
        public virtual ObjectResult<get_all_course_tags_Result> get_all_course_tags(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_all_course_tags_Result>("get_all_course_tags", idParameter);
        }
    
        public virtual ObjectResult<get_all_finished_courses_for_user_Result> get_all_finished_courses_for_user(string id)
        {
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_all_finished_courses_for_user_Result>("get_all_finished_courses_for_user", idParameter);
        }
    
        public virtual ObjectResult<get_all_friend_requests_Result> get_all_friend_requests(string id)
        {
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_all_friend_requests_Result>("get_all_friend_requests", idParameter);
        }
    
        public virtual ObjectResult<get_all_friends_Result> get_all_friends(string id)
        {
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_all_friends_Result>("get_all_friends", idParameter);
        }
    
        public virtual ObjectResult<get_all_not_finished_courses_for_user_Result> get_all_not_finished_courses_for_user(string id)
        {
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_all_not_finished_courses_for_user_Result>("get_all_not_finished_courses_for_user", idParameter);
        }
    
        public virtual ObjectResult<get_all_un_archived_courses_for_user_Result> get_all_un_archived_courses_for_user(string id)
        {
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_all_un_archived_courses_for_user_Result>("get_all_un_archived_courses_for_user", idParameter);
        }
    
        public virtual ObjectResult<get_all_un_archived_work_groups_for_user_Result> get_all_un_archived_work_groups_for_user(string id)
        {
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_all_un_archived_work_groups_for_user_Result>("get_all_un_archived_work_groups_for_user", idParameter);
        }
    
        public virtual ObjectResult<Get_all_unarchived_courses_Result> Get_all_unarchived_courses()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_all_unarchived_courses_Result>("Get_all_unarchived_courses");
        }
    
        public virtual ObjectResult<Get_all_unarchived_groups_Result> Get_all_unarchived_groups()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_all_unarchived_groups_Result>("Get_all_unarchived_groups");
        }
    
        public virtual ObjectResult<get_all_work_group_mempers_Result> get_all_work_group_mempers(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_all_work_group_mempers_Result>("get_all_work_group_mempers", idParameter);
        }
    
        public virtual ObjectResult<get_all_work_group_tags_Result> get_all_work_group_tags(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_all_work_group_tags_Result>("get_all_work_group_tags", idParameter);
        }
    
        public virtual ObjectResult<get_certificates_by_inst_id_Result> get_certificates_by_inst_id(string inst_id)
        {
            var inst_idParameter = inst_id != null ?
                new ObjectParameter("inst_id", inst_id) :
                new ObjectParameter("inst_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_certificates_by_inst_id_Result>("get_certificates_by_inst_id", inst_idParameter);
        }
    
        public virtual int remove_friend_or_frequest(string reciver, string sender)
        {
            var reciverParameter = reciver != null ?
                new ObjectParameter("reciver", reciver) :
                new ObjectParameter("reciver", typeof(string));
    
            var senderParameter = sender != null ?
                new ObjectParameter("sender", sender) :
                new ObjectParameter("sender", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("remove_friend_or_frequest", reciverParameter, senderParameter);
        }
    
        public virtual ObjectResult<search_all_Result> search_all(string name)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<search_all_Result>("search_all", nameParameter);
        }
    
        public virtual ObjectResult<search_courses_Result> search_courses(string name)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<search_courses_Result>("search_courses", nameParameter);
        }
    
        public virtual ObjectResult<search_courses_WGroup_Result> search_courses_WGroup(string name)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<search_courses_WGroup_Result>("search_courses_WGroup", nameParameter);
        }
    
        public virtual ObjectResult<search_tags_Result> search_tags(string name)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<search_tags_Result>("search_tags", nameParameter);
        }
    
        public virtual ObjectResult<search_users_Result> search_users(string name)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<search_users_Result>("search_users", nameParameter);
        }
    
        public virtual ObjectResult<search_work_groups_Result> search_work_groups(string name)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<search_work_groups_Result>("search_work_groups", nameParameter);
        }
    
        public virtual int send_friend_request(string reciver, string sender, Nullable<System.DateTime> date)
        {
            var reciverParameter = reciver != null ?
                new ObjectParameter("reciver", reciver) :
                new ObjectParameter("reciver", typeof(string));
    
            var senderParameter = sender != null ?
                new ObjectParameter("sender", sender) :
                new ObjectParameter("sender", typeof(string));
    
            var dateParameter = date.HasValue ?
                new ObjectParameter("date", date) :
                new ObjectParameter("date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("send_friend_request", reciverParameter, senderParameter, dateParameter);
        }
    
        public virtual int un_archive_course(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("un_archive_course", idParameter);
        }
    
        public virtual int un_archive_work_group(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("un_archive_work_group", idParameter);
        }
    }
}
