//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace live.courses.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class post
    {
        public int id { get; set; }
        public string user_id { get; set; }
        public string group_type { get; set; }
        public Nullable<int> group_id { get; set; }
        public string title { get; set; }
        public string body { get; set; }
        public string image { get; set; }
        public Nullable<System.DateTime> timestamp { get; set; }
        public int likes_number { get; set; }
        public int comments_number { get; set; }
        public IEnumerable<comment> post_comments { get; set; }
        public HttpPostedFileBase imagefile { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
