//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace live.courses.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class work_group
    {
        public work_group()
        {
            this.Work_group_members = new HashSet<Work_group_members>();
            this.work_group_tags = new HashSet<work_group_tags>();
            this.group_comment = new HashSet<group_comment>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string about { get; set; }
        public Nullable<System.DateTime> creating_date { get; set; }
        public string place { get; set; }
        public string trange { get; set; }
        public Nullable<bool> availlable { get; set; }
        public string way_to_apply { get; set; }
        public string notes { get; set; }
        public string admin { get; set; }
        public string category { get; set; }
        public string video { get; set; }
        public Nullable<bool> Archived { get; set; }
        public string room_id { get; set; }
    
        public virtual ICollection<Work_group_members> Work_group_members { get; set; }
        public virtual ICollection<work_group_tags> work_group_tags { get; set; }
        public virtual ICollection<group_comment> group_comment { get; set; }
    }
}
